test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

yandex:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:yandex, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:yandex, :secret_access_key) %>
  region: ru-central3
  bucket: qnaa
  endpoint: 'https://storage.yandexcloud.net'
  force_path_style: true
